### ISSUE TITLE
Not working with path with unicode chars

### ISSUE THREAD

**Issue by overdrive80** [dan0v/xdelta3-cross-gui#21]
If source files is located in paths with unicode chars, f.e. '´', will not create vcdiff files and program finalize without advise that one error ocurrs because any files was created.

**Comment by dan0v** [comment]
[Version 1.1.5](https://github.com/dan0v/xdelta3-cross-gui/releases/tag/1.1.5) will display an error prompt if this, or other errors are encountered during xDelta3 execution. This doesn't solve the underlying issue, but will at least show the issue and not display a false success message.

**Comment by 1024mb** [comment]
this could be fixed by adding `CHCP 65001` to the start of the batch file at least for Windows (don't know if Linux/Mac have this problem)

**Comment by dan0v** [comment]
@1024mb if you have a working solution (even if only for Windows - I haven't tested this behavior on other platforms either) I'd appreciate if you could open a PR with your fix
