### ISSUE TITLE
File name typo at version 1.1.5

### ISSUE THREAD

**Issue by issaclin32** [dan0v/xdelta3-cross-gui#22]
There is a typo in the filename.

It is a minor issue. However some package installers such as *Chocolatey* or *Scoop* may have problem parsing it.

`xdelta3-cross-gui_1.1.5._win_x86.zip` -> should be `xdelta3-cross-gui_1.1.5_win_x86.zip`

**Comment by dan0v** [comment]
Thanks for pointing that out. I've changed release naming to be standard between releases by not including version numbers in the zip name.

Future releases will be names
xdelta3-cross-gui_linux_AppImage_x86_64.tar.gz
xdelta3-cross-gui_macOS_x86_64.tar.gz
xdelta3-cross-gui_win_x86.zip
