### ISSUE TITLE
"Applied patch" output is identical to input xdelta file

### ISSUE THREAD

**Issue by TDuffinNTU** [dan0v/xdelta3-cross-gui#29]
So I'm trying to patch a PS2 ISO, with a supplied .xdelta file. I go through the following steps:

1. place ROM ISO in "old file" side
2. place mod.xdelta file in "new file" side
3. Generate using default settings
4. Open output folder, place original ROM ISO into "original" folder
5. mark linux .sh file as executable
6. right click and run in console
7. press enter when prompted
8. inspect "output" folder

Expected:

"output" folder contains ROM ISO with patches applied

Actual:

"output" folder contains .xdelta file with identical md5sum to input.

System info

Steam OS 3.5
KDE Plasma 5.27

***

Maybe I'm using the app wrong? There isnt any documentation beyond the READMEs and what I've been told to do with similar apps so I could easily be doing something wrong.

**Comment by dan0v** [comment]
Hi, this tool is just for generating patches, not for applying them in the UI (although that has been an extension I've wanted to do for ages). In your case, all you have to do to apply an existing patch to your original file is something like `xdelta3 -v -d -s "original_file_path" "xdelta_patch_file_path" "output_file_path"` in your terminal. You can find the xdelta3 manual [here](https://github.com/jmacd/xdelta/blob/wiki/CommandLineSyntax.md) or by typing `xdelta3 -h` in your terminal. You will need to have installed xdelta3 with a package manager, or manually downloaded the binary (also found at the previous link).
