### ISSUE TITLE
[Feature Request] Make multithreading optional

### ISSUE THREAD

**Issue by McBaws** [dan0v/xdelta3-cross-gui#35]
If you have more than a handful of large files, running all of the xdelta processes in parallel can be very slow with default settings, even eating up all the memory and crippling the computer.

I don't want to have to worry about tuning my source window size settings, so please add a toggle for multithreading or make the number of processes that run in parallel customizable. Thanks!

**Comment by dan0v** [comment]
Resolved in [Version 1.7.1](https://github.com/dan0v/xdelta3-cross-gui/releases/tag/1.7.1)
