### ISSUE TITLE
AppImage crashes when clicking the "+" sign to select files.

### ISSUE THREAD

**Issue by damian101** [dan0v/xdelta3-cross-gui#8]
I'm running RebornOS (Arch Linux) with KDE Plasma 5.21 as the desktop environment.

**Comment by dan0v** [comment]
Thanks for the ticket, does it also crash when clicking the + sign if you use the [unpackaged Linux build](https://github.com/dan0v/xdelta3-cross-gui/releases/download/1.0.4/xdelta3-cross-gui_1.0.4_linux_x86_64.tar.gz)?

**Comment by dan0v** [comment]
Testing it in Manjaro 20.2.1 (KDE) confirms that both the AppImage and unpackaged builds crash when trying to open the file chooser window.

**Comment by dan0v** [comment]
Resolved in [Version 1.0.5](https://github.com/dan0v/xdelta3-cross-gui/releases/tag/1.0.5)
